### ISSUE TITLE
can't differentiate two non-usb serial devices

### ISSUE THREAD

**Issue by stevenxdyoung** [WICG/serial#155] opened 2021-12-31 17:56 UTC
The getinfo() only return vendorID and prodID, but it will be undefined when non-usb device connected, so it can't differentiate the two non-usb serial devices(like COM1 and COM2) by using getinfo(). Is it possible let getinfo() return device path, therefore the serial number can be extracted from device path, thanks.

**Comment by reillyeon** [comment] 2022-02-23 00:49
This is a duplicate of #128. The solution won't be to provide the device path directly but to provide an identifier which will be used consistently to refer to the port with that path. That indirection is necessary as a privacy-preserving mechanism.

**Closed by reillyeon** 2022-02-23 00:49 UTC
