### ISSUE TITLE
Get more information - chrome device log

### ISSUE THREAD

**Issue by SebCanet** [WICG/serial#154] opened 2021-12-27 14:03 UTC
Hi,
I think this has surely been discused (sorry, but I did not found something) but I would like to get USB device information with getInfo().
This information are available in 'chrome://device-log/', like name, path, vendorId/producId already even if they are available from getInfo().
Is it possible to enhance getInfo() and get additionnal information?
Many thanks.

**Comment by tmtron** [comment] 2022-08-19 12:11
I'd also like to get some more info: e.g. the port-name (i.e. path) would be good so that the user can identify which port it is when we have access to multiple ports

**Comment by reillyeon** [comment] 2023-01-03 23:29
Closing this as a duplicate of #128 and #175 which I'm using to track use cases for two specific pieces of information that would be useful to include in `getInfo()`.

**Closed by reillyeon** 2023-01-03 23:29 UTC
